services:
  - type: web
    name: react-router-app
    env: node
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
    # Ensure this is treated as a Node.js app, not a static site
    autoDeploy: true
